package scala.meta.internal.mtags

import java.nio.CharBuffer

import scala.util.control.NonFatal

import scala.meta.Dialect
import scala.meta.internal.io.PlatformFileIO
import scala.meta.internal.metals.JdkVersion0
import scala.meta.internal.mtags.MtagsEnrichments._
import scala.meta.internal.semanticdb.Scala._
import scala.meta.internal.{semanticdb => s}
import scala.meta.io.AbsolutePath
import java.nio.file.Path
import java.nio.file.Files
import java.util.zip.ZipFile
import scala.meta.inputs.Input
import scala.meta.pc.reports.ReportContext
import scala.collection.mutable.ListBuffer

/**
 * Index split on buckets per dialect in order to have a constant time
 * and low memory footprint to infer dialect for SymbolDefinition because
 * it's used in WorkspaceSymbolProvider
 *
 * @param toplevels keys are non-trivial toplevel symbols and values are the file
 *                  the symbols are defined in.
 * @param definitions keys are global symbols and the values are the files the symbols
 *                    are defined in. Difference between toplevels and definitions
 *                    is that toplevels contains only symbols generated by ScalaToplevelMtags
 *                    while definitions contains only symbols generated by ScalaMtags.
 */
class SymbolIndexBucket(
    val toplevels: AtomicTrieMap[String, Set[
      (SourcePath, Option[Either[AbsolutePath, GlobalSymbolIndex.Module]])
    ]],
    val definitions: AtomicTrieMap[String, Set[SymbolLocation]],
    val sourceJars: OpenClassLoader,
    toIndexSource: AbsolutePath => AbsolutePath = identity,
    mtags: Mtags,
    dialectOpt: Option[Dialect],
    onError: PartialFunction[Throwable, Unit],
    javaHome: Path,
    javaOnly: Boolean,
    addTextDocuments: (
        SymbolIndexBucket,
        Option[Either[AbsolutePath, GlobalSymbolIndex.Module]],
        SourcePath,
        s.TextDocuments
    ) => Unit
) {

  var logger: java.util.function.Consumer[String] = null

  def duplicate(
      dialectOpt: Option[Dialect],
      javaOnly: Boolean
  ): SymbolIndexBucket = {
    assert(this.javaOnly || this.dialectOpt == dialectOpt)
    new SymbolIndexBucket(
      toplevels.duplicate(),
      definitions.duplicate(),
      sourceJars.duplicate(),
      toIndexSource,
      mtags,
      dialectOpt,
      onError,
      javaHome,
      javaOnly,
      addTextDocuments
    )
  }

  def close(): Unit = () // sourceJars.close()

  // called for directories in dependency sources
  def addSourceDirectory(
      dir: AbsolutePath
  )(implicit rc: ReportContext): List[IndexingResult] = {
    if (sourceJars.addEntry(dir.toNIO)) {
      val sources = dir.listRecursive.toVector
      val scalaSources = ListBuffer.empty[AbsolutePath]
      val javaSources = ListBuffer.empty[AbsolutePath]
      for (source <- sources) {
        if (source.isScala)
          scalaSources += source
        else if (source.isJava)
          javaSources += source
      }
      if (logger != null && (scalaSources.nonEmpty || javaSources.nonEmpty))
        logger.accept {
          "Indexing " +
            Seq(
              if (scalaSources.isEmpty) Nil
              else
                Seq(
                  s"${scalaSources.length} Scala ${if (scalaSources.length == 1) "source"
                    else "sources"}"
                ),
              if (javaSources.isEmpty) Nil
              else
                Seq(s"${javaSources.length} Java ${if (javaSources.length == 1) "source"
                  else "sources"}")
            ).flatten.mkString(" and ") +
            s" under $dir"
        }
      def scalaResults = scalaSources.iterator
        .flatMap { scalaSource =>
          addSourceFile(
            Some(Left(dir)),
            scalaSource.toInput,
            isJava = false
          ).iterator
        }
      def javaResults = javaSources.iterator
        .flatMap { javaSource =>
          val topLevels = addJavaSourceFile(Some(Left(dir)), javaSource.toInput)
          if (topLevels.isEmpty) Iterator.empty
          else
            Iterator(
              IndexingResult(
                SourcePath.Standard(javaSource.toNIO),
                topLevels,
                overrides = Nil
              )
            )
        }
      (scalaResults ++ javaResults).toList
    } else {
      if (logger != null)
        logger.accept(s"$dir directory already indexed")
      List.empty
    }
  }

  // called for JDK sources (standard modules) and Scala library sources (standalone modules)
  // TODO use addIndexedSourceJar instead?
  def addSourceJar(
      jar: AbsolutePath,
      isPureJava: Boolean = false
  )(implicit
      ctx: SourcePath.Context,
      rc: ReportContext
  ): List[IndexingResult] = {
    if (sourceJars.addEntry(jar.toNIO))
      ctx
        .entries(jar.toNIO)
        .flatMap { source =>
          if (source.uri.endsWith(".scala") && !isPureJava)
            addSourceFile(None, source.toInput, isJava = false)
          else if (source.uri.endsWith(".java"))
            // addSourceFile(source.toInput, isJava = true) // ?
            addJavaSourceFile(None, source.toInput) match {
              case Nil => None
              case topLevels =>
                Some(IndexingResult(source, topLevels, overrides = Nil))
            }
          else
            None
        }
        .toList
    else
      List.empty
  }

  // not called anymore (???)
  def indexSourceJar(jar: AbsolutePath, isJava: Boolean)(implicit
      ctx: SourcePath.Context
  ): List[IndexingResult] =
    ctx
      .entries(jar.toNIO)
      .filter(_.pathInZip.endsWith(".scala"))
      .map(source => indexSource(source.toInput, isJava = isJava))
      .toList

  // called for cached JARs in dependency sources
  def addIndexedSourceJar(
      jar: AbsolutePath,
      symbols: List[(String, SourcePath.ZipEntry)]
  ): Unit = {
    if (sourceJars.addEntry(jar.toNIO)) {
      symbols.foreach { case (sym, path) =>
        toplevels.updateWith(sym) {
          case Some(acc) => Some(acc + (path -> None))
          case None => Some(Set(path -> None))
        }
      }
    }
    PlatformFileIO.newJarFileSystem(jar, create = false)
  }

  /* Sometimes source jars have additional nested directories,
   * in that case java toplevel is not "trivial".
   * See: https://github.com/scalameta/metals/issues/3815
   */
  private def addJavaSourceFile(
      originOpt: Option[Either[AbsolutePath, GlobalSymbolIndex.Module]],
      input: Input.VirtualFile
  )(implicit rc: ReportContext): List[String] = {
    new JavaToplevelMtags(
      input,
      includeInnerClasses = false
    ).readPackage match {
      case Nil => Nil
      case packageParts =>
        val relPathOpt = SourcePath(input.path) match {
          case z: SourcePath.ZipEntry =>
            Some(z.pathInZip)
          case s: SourcePath.Standard =>
            originOpt match {
              case Some(Left(dir)) =>
                Some(dir.toNIO.relativize(s.path).toString)
              case _ =>
                None
            }
        }
        val className = input.path.split('/').last.stripSuffix(".java")
        val symbol = packageParts.mkString("", "/", s"/$className#")
        val isTrivialToplevelSymbol0 = relPathOpt
          .exists { subPath =>
            isTrivialToplevelSymbol(
              subPath,
              symbol,
              extension = "java"
            )
          }
        if (isTrivialToplevelSymbol0) Nil
        else {
          toplevels.updateWith(symbol) {
            case Some(acc) => Some(acc + (SourcePath(input.path) -> originOpt))
            case None => Some(Set(SourcePath(input.path) -> originOpt))
          }
          List(symbol)
        }
    }
  }

  private def addSourceFile(
      originOpt: Option[Either[AbsolutePath, GlobalSymbolIndex.Module]],
      input: Input.VirtualFile,
      isJava: Boolean
  ): Option[IndexingResult] = try {
    val IndexingResult(path, topLevels, overrides) =
      indexSource(input, isJava)
    topLevels.foreach { symbol =>
      toplevels.updateWith(symbol) {
        case Some(acc) => Some(acc + (SourcePath(input.path) -> originOpt))
        case None => Some(Set(SourcePath(input.path) -> originOpt))
      }
    }
    Some(IndexingResult(path, topLevels, overrides))
  } catch {
    case NonFatal(e) =>
      onError(e)
      None
  }

  // called for not-yet-cached entries of JARs in dependency sources (TODO use indexSourceJar instead?)
  def indexSource(
      input: Input.VirtualFile,
      isJava: Boolean
  ): IndexingResult = {
    val source = SourcePath(input.path)
    val (doc, overrides) = mtags.indexWithOverrides(input, dialectOpt)
    val sourceTopLevels =
      doc.occurrences.iterator
        .filterNot(_.symbol.isPackage)
        .map(_.symbol)
    val topLevels =
      if (input.path.isScalaScript) sourceTopLevels.toList
      else if (isJava) {
        sourceTopLevels.toList.headOption
          .filter(sym => !isTrivialToplevelSymbol(input.path, sym, "java"))
          .toList
      } else
        AbsolutePath(input.path).toIdeallyRelativeURI() match {
          case Some(subPath) =>
            sourceTopLevels
              .filter(sym => !isTrivialToplevelSymbol(subPath, sym, "scala"))
              .toList
          case None =>
            sourceTopLevels.toList
        }
    IndexingResult(source, topLevels, overrides)
  }

  // Returns true if symbol is com/foo/Bar# and path is /com/foo/Bar.scala
  // Such symbols are "trivial" because their definition location can be computed
  // on the fly.
  private def isTrivialToplevelSymbol(
      path: String,
      symbol: String,
      extension: String = "scala"
  ): Boolean = {
    val pathBuffer =
      CharBuffer.wrap(path).subSequence(1, path.length - extension.length - 1)
    val symbolBuffer =
      CharBuffer.wrap(symbol).subSequence(0, symbol.length - 1)
    pathBuffer.equals(symbolBuffer)
  }

  // called for workspaces sources by indexer and file watcher
  def addToplevelSymbol(
      path: String,
      module: GlobalSymbolIndex.Module,
      source: SourcePath,
      toplevel: String
  ): Unit = {
    if (source.isScalaScript || !isTrivialToplevelSymbol(path, toplevel)) {
      toplevels.updateWith(toplevel) {
        case Some(acc) => Some(acc + (source -> Some(Right(module))))
        case None => Some(Set(source -> Some(Right(module))))
      }
    }
  }

  def findFileForToplevel(
      topLevelSymbol: Symbol
  )(implicit ctx: SourcePath.Context): List[(SourcePath, Option[Dialect])] = {
    toplevels
      .get(topLevelSymbol.toString())
      .map(_.toList.map(_._1))
      .orElse(loadFromSourceJars(trivialPaths(topLevelSymbol)).map(_.map(_._2)))
      .orElse(loadFromSourceJars(modulePaths(topLevelSymbol)).map(_.map(_._2)))
      .getOrElse(Nil)
      .map(x => (x, dialectOpt))
  }

  def query(symbol: Symbol): List[SymbolDefinition] =
    SourcePath.withContext { implicit ctx =>
      query0(symbol, symbol)
    }

  /**
   * Returns the file where symbol is defined, if any.
   *
   * Uses two strategies to recover from missing symbol definitions:
   * - try to enter the toplevel symbol definition, then lookup symbol again.
   * - if the symbol is synthetic, for examples from a case class of macro annotation,
   *  fall back to related symbols from the enclosing class, see `DefinitionAlternatives`.
   *
   * @param querySymbol The original symbol that was queried by the user.
   * @param symbol The symbol that
   * @return
   */
  private def query0(
      querySymbol: Symbol,
      symbol: Symbol
  )(implicit ctx: SourcePath.Context): List[SymbolDefinition] = {

    removeOldEntries(symbol)

    // Fallback 1: enter the toplevel symbol definition
    if (!definitions.contains(symbol.value)) {
      toplevels.get(symbol.toplevel.value) match {
        case Some(files) =>
          for ((source, originOpt) <- files)
            addMtagsSourceFile(originOpt, source.toInput)
        case _ =>
          val fromTrivialPaths = loadFromSourceJars(
            trivialPaths(symbol.toplevel)
          )
          def fromModulePaths = loadFromSourceJars(modulePaths(symbol.toplevel))
          for {
            list <- fromTrivialPaths.orElse(fromModulePaths)
            (originOpt, path) <- list
          } addMtagsSourceFile(
            originOpt.map(path0 => Left(AbsolutePath(path0))),
            path.toInput
          )
      }
    }

    // Fallback 2: try with files for companion class
    if (
      !definitions.contains(symbol.value) && symbol.toplevel.value.endsWith(".")
    ) {
      val toplevelAlternative = s"${symbol.toplevel.value.stripSuffix(".")}#"
      lazy val fileSet = toplevels.get(symbol.toplevel.value).map(_.map(_._1))
      for {
        (companionClassFile, originOpt) <- toplevels
          .get(toplevelAlternative)
          .toSet
          .flatten
        if !fileSet.exists(_.contains(companionClassFile))
      } addMtagsSourceFile(originOpt, companionClassFile.toInput)
    }

    definitions.get(symbol.value) match {
      case Some(paths) =>
        paths.toList.map { location =>
          SymbolDefinition(
            querySymbol = querySymbol,
            definitionSymbol = symbol,
            path = location.path,
            dialectOpt = dialectOpt,
            range = location.range,
            kind = None,
            properties = 0
          )
        }
      case None =>
        // Fallback 3: guess related symbols from the enclosing class.
        DefinitionAlternatives(symbol).flatMap(query0(querySymbol, _))
    }
  }

  /**
   * Remove possible old, outdated entries from the toplevels and definitions.
   * This action is performed when a symbol is queried, to avoid returning incorrect results.
   */
  private def removeOldEntries(
      symbol: Symbol
  )(implicit ctx: SourcePath.Context): Unit = {
    val exists =
      (toplevels
        .get(symbol.value)
        .map(_.map(_._1))
        .getOrElse(Set.empty) ++ definitions
        .get(symbol.value)
        .map(_.map(_.path))
        .getOrElse(Set.empty)).filter(_.exists())

    toplevels.updateWith(symbol.value) {
      case None => None
      case Some(acc) =>
        val updated = acc.filter(t => exists(t._1))
        if (updated.isEmpty) None
        else Some(updated)
    }

    definitions.updateWith(symbol.value) {
      case None => None
      case Some(acc) =>
        val updated = acc.filter(loc => exists(loc.path))
        if (updated.isEmpty) None
        else Some(updated)
    }
  }

  private def toIndexInput(
      input: Input.VirtualFile
  )(implicit ctx: SourcePath.Context): Input.VirtualFile =
    SourcePath(input.path) match {
      case s: SourcePath.Standard =>
        val toIndex = toIndexSource(AbsolutePath(s.path))
        if (toIndex.toNIO == s.path) input
        else
          s.copy(path = toIndex.toNIO).toInput
      case _: SourcePath.ZipEntry =>
        input
    }

  private def allSymbols(
      input: Input.VirtualFile
  )(implicit ctx: SourcePath.Context): s.TextDocument = {
    val toIndexInput0 = toIndexInput(input)
    mtags.allSymbols(toIndexInput0, dialectOpt)
  }

  private def extension(filename: String): String = {
    val idx = filename.lastIndexOf('.')
    if (idx == -1) ""
    else filename.substring(idx + 1)
  }

  // similar as addSourceFile except indexes all global symbols instead of
  // only non-trivial toplevel symbols.
  private def addMtagsSourceFile(
      originOpt: Option[Either[AbsolutePath, GlobalSymbolIndex.Module]],
      input: Input.VirtualFile,
      retry: Boolean = true
  )(implicit ctx: SourcePath.Context): Unit = try {
    val docs: s.TextDocuments = extension(input.path) match {
      case "scala" | "java" | "sc" =>
        val document = allSymbols(input)
        s.TextDocuments(List(document))
      case _ =>
        s.TextDocuments(Nil)
    }
    if (docs.documents.nonEmpty) {
      addTextDocuments(this, originOpt, SourcePath(input.path), docs)
    }
  } catch {
    case NonFatal(e) =>
      // pprint.err.log("Error indexing " + input.path)
      // e.printStackTrace(System.err)
      // logger.log(Level.WARNING, s"Error indexing ${input.path}", e)
      scribe.error(s"Error indexing ${input.path}", e)
      if (retry) addMtagsSourceFile(originOpt, input, retry = false)
  }

  // Returns the first path that resolves to a file.
  private def loadFromSourceJars(
      paths: List[String]
  )(implicit
      ctx: SourcePath.Context
  ): Option[List[(Option[Path], SourcePath)]] = {
    paths match {
      case Nil => None
      case head :: tail =>
        val files = sourceJars
          .list()
          .iterator
          .map { path =>
            if (Files.isDirectory(path))
              (Some(path), SourcePath.Standard(path.resolve(head)))
            else (None, SourcePath.ZipEntry(path, head, -1L))
          }
          .filter { case (_, ent) => ent.exists() }
          .toList
        if (files.isEmpty) loadFromSourceJars(tail)
        else Some(files)
    }
  }

  // Returns relative file paths for trivial toplevel symbols, example:
  // Input:  scala/collection/immutable/List#
  // Output: scala/collection/immutable/List.scala
  //         scala/collection/immutable/List.java
  private def trivialPaths(toplevel: Symbol): List[String] = {
    val noExtension = toplevel.value.stripSuffix(".").stripSuffix("#")
    List(
      noExtension + ".scala",
      noExtension + ".java"
    )
  }

  private lazy val modules = {
    val srcZipCandidates =
      Seq(javaHome.resolve("src.zip"), javaHome.resolve("lib/src.zip"))
    val srcZip = srcZipCandidates.filter(Files.exists(_)).headOption.getOrElse {
      sys.error(s"src.zip not found among $srcZipCandidates")
    }
    val zf = new ZipFile(srcZip.toFile)
    try {
      import scala.jdk.CollectionConverters._
      zf.entries()
        .asScala
        .map(_.getName)
        .filter(_.endsWith("/module-info.java"))
        .map(_.stripSuffix("/module-info.java"))
        .filter(!_.contains("/"))
        .toList
    } finally {
      zf.close()
    }
  }

  private lazy val javaVer =
    JdkVersion0.fromJavaHome(javaHome).getOrElse {
      sys.error(s"Cannot get Java version of $javaHome")
    }
  private def modulePaths(toplevel: Symbol): List[String] =
    if (javaVer.major >= 9) {
      val noExtension = toplevel.value.stripSuffix(".").stripSuffix("#")
      modules.flatMap { module =>
        List(
          s"$module/$noExtension.java",
          s"$module/$noExtension.scala"
        )
      }
    } else
      Nil
}

object SymbolIndexBucket {

  def empty(
      dialectOpt: Option[Dialect],
      mtags: Mtags,
      sourceJars: OpenClassLoader,
      toIndexSource: AbsolutePath => AbsolutePath,
      onError: PartialFunction[Throwable, Unit],
      javaHome: Path,
      javaOnly: Boolean,
      addTextDocuments: (
          SymbolIndexBucket,
          Option[Either[AbsolutePath, GlobalSymbolIndex.Module]],
          SourcePath,
          s.TextDocuments
      ) => Unit
  ): SymbolIndexBucket =
    new SymbolIndexBucket(
      AtomicTrieMap.empty,
      AtomicTrieMap.empty,
      sourceJars,
      toIndexSource,
      mtags,
      dialectOpt,
      onError,
      javaHome,
      javaOnly,
      addTextDocuments
    )

}
